# Generated by Django 5.1 on 2024-09-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DadosClinicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.CharField(choices=[('A/P', 'Altura/Peso'), ('FC', 'Frequencia Cardiaca'), ('P', 'Pressão'), ('T', 'Temperatura')], max_length=30)),
                ('resultado', models.CharField(max_length=30)),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.pacientes')),
            ],
        ),
    ]
